### PR TITLE
refactor: simplify the inception resnet v2 model definition code

### PR DESCRIPTION
**Pull request by bpradana**
simplify the inception resnet v2 code

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
Excellent work. Thank you.
Can you handle to resolve conflicts ?

**Comment by bpradana** [comment]
Of course! just wait a moment!

**Comment by AndreaLanfranchi** [comment]
Hey @bpradana,
the code has diverged too much right now.
Trying to do some serious refactoring. I am sorry I probably wasted your time.
Maybe you want to come back when I'm finihed ?

**Comment by AndreaLanfranchi** [comment]
Actually refactored

**Pull request closed without merging**
